'use client';

/**
 * Ticker search with keyboard navigation.
 *
 * One of only three client components in the app. Uses useTransition so that
 * navigation is optimistic: the button enters its pending state on the very
 * first keystroke of Enter, while the server renders the new page. The old
 * build pushed the route and left the user staring at an unchanged screen.
 *
 * Search matches on symbol *or* company name against the full listed US
 * universe (~5,300 names), generated by `scripts/build-symbol-index.mjs` into
 * `public/symbols.json`. That file is fetched once, lazily, on first
 * interaction rather than at page load, so it never competes with the initial
 * render and costs nothing for a visitor who does not search.
 *
 * Deliberately no upstream lookup per keystroke: Finnhub's free tier allows 60
 * requests a minute and one cold analysis already spends about 15, so a
 * type-ahead hitting the API would starve the actual product.
 */

import {
  useState,
  useRef,
  useEffect,
  useMemo,
  useTransition,
  type FormEvent,
  type KeyboardEvent,
} from 'react';
import { useRouter } from 'next/navigation';

/** `[symbol, company name]`. Tuples rather than objects to halve the payload. */
type Entry = [string, string];

/**
 * Used only if `/symbols.json` cannot be fetched, so the box still suggests
 * something rather than appearing broken. Any symbol remains submittable
 * regardless of whether it appears here.
 */
const FALLBACK: Entry[] = [
  ['AAPL', 'Apple Inc'],
  ['MSFT', 'Microsoft Corp'],
  ['GOOGL', 'Alphabet Inc Class A'],
  ['AMZN', 'Amazon.com Inc'],
  ['NVDA', 'NVIDIA Corp'],
  ['META', 'Meta Platforms Inc Class A'],
  ['TSLA', 'Tesla Inc'],
  ['JPM', 'JPMorgan Chase & Co'],
];

/* Module scope, so the index is fetched once per page load no matter how many
   search boxes mount (the ticker page renders one in its top bar). */
let indexCache: Entry[] | null = null;
let indexRequest: Promise<Entry[]> | null = null;

function loadIndex(): Promise<Entry[]> {
  if (indexCache) return Promise.resolve(indexCache);
  if (!indexRequest) {
    indexRequest = fetch('/symbols.json')
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`HTTP ${r.status}`))))
      .then((data: Entry[]) => {
        indexCache = data;
        return data;
      })
      .catch(() => {
        indexCache = FALLBACK;
        return FALLBACK;
      });
  }
  return indexRequest;
}

/**
 * Relevance tier, lowest first. The ordering matters more than the matching:
 * typing "co" should not bury Coca-Cola under every company with "co" buried
 * mid-name, and typing a full symbol should always put that symbol first.
 *
 * `wordStart` is built once per query rather than per row; constructing a
 * RegExp 5,300 times per keystroke is the kind of thing that makes a type-ahead
 * feel sticky.
 */
function rank(symbol: string, upperName: string, q: string, wordStart: RegExp): number {
  if (symbol === q) return 0;
  if (symbol.startsWith(q)) return 1;
  if (upperName.startsWith(q)) return 2;
  // A word inside the name starting with the query, e.g. "chase" -> JPMorgan Chase.
  if (wordStart.test(upperName)) return 3;
  if (upperName.includes(q)) return 4;
  return -1;
}

const MAX_SUGGESTIONS = 8;

export function TickerSearch({
  size = 'large',
  placeholder = 'Search by ticker or company name',
  autoFocus = false,
}: {
  size?: 'large' | 'compact';
  placeholder?: string;
  autoFocus?: boolean;
}) {
  const router = useRouter();
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState(false);
  const [highlighted, setHighlighted] = useState(0);
  const [isPending, startTransition] = useTransition();
  const [index, setIndex] = useState<Entry[] | null>(indexCache);

  const containerRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  /** Pulled in on first focus or first keystroke, never on mount. */
  function ensureIndex() {
    if (indexCache) {
      if (!index) setIndex(indexCache);
      return;
    }
    loadIndex().then(setIndex);
  }

  const matches = useMemo(() => {
    const q = query.trim().toUpperCase();
    if (!q || !index) return [];

    // Scans the whole universe every keystroke, deliberately. An early break
    // would be wrong, not just approximate: the index is ordered by symbol, so
    // capping the scan for a query like "V" fills up on mid-name matches from
    // the A's and never reaches Visa. ~5,300 rows costs well under a
    // millisecond, which is far cheaper than a wrong first suggestion.
    const wordStart = new RegExp(`\\b${q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`);
    const scored: Array<{ entry: Entry; tier: number }> = [];
    for (const entry of index) {
      const tier = rank(entry[0], entry[1].toUpperCase(), q, wordStart);
      if (tier >= 0) scored.push({ entry, tier });
    }

    return scored
      .sort(
        (a, b) =>
          a.tier - b.tier ||
          a.entry[0].length - b.entry[0].length ||
          a.entry[0].localeCompare(b.entry[0])
      )
      .slice(0, MAX_SUGGESTIONS)
      .map((s) => s.entry);
  }, [query, index]);

  useEffect(() => {
    setHighlighted(0);
    setOpen(matches.length > 0);
  }, [matches.length, query]);

  useEffect(() => {
    function onPointerDown(e: MouseEvent) {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener('mousedown', onPointerDown);
    return () => document.removeEventListener('mousedown', onPointerDown);
  }, []);

  // Focus the search from anywhere with "/", the convention users expect.
  useEffect(() => {
    function onKey(e: globalThis.KeyboardEvent) {
      if (e.key === '/' && document.activeElement !== inputRef.current) {
        e.preventDefault();
        inputRef.current?.focus();
      }
    }
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, []);

  function go(symbol: string) {
    const clean = symbol.trim().toUpperCase();
    if (!clean) return;
    setOpen(false);
    startTransition(() => router.push(`/ticker/${encodeURIComponent(clean)}`));
  }

  function onSubmit(e: FormEvent) {
    e.preventDefault();
    go(matches.length > 0 && open ? matches[highlighted][0] : query);
  }

  function onKeyDown(e: KeyboardEvent<HTMLInputElement>) {
    if (!open || matches.length === 0) return;
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setHighlighted((h) => (h + 1) % matches.length);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setHighlighted((h) => (h - 1 + matches.length) % matches.length);
    } else if (e.key === 'Escape') {
      setOpen(false);
    }
  }

  const big = size === 'large';

  return (
    <div ref={containerRef} className="relative w-full">
      <form onSubmit={onSubmit}>
        <div className="relative">
          <span
            className="pointer-events-none absolute top-1/2 left-4 -translate-y-1/2"
            style={{ color: 'var(--text-tertiary)' }}
            aria-hidden="true"
          >
            <svg
              width="17"
              height="17"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2.2"
              strokeLinecap="round"
            >
              <circle cx="11" cy="11" r="7" />
              <path d="m20 20-3.5-3.5" />
            </svg>
          </span>

          <input
            ref={inputRef}
            value={query}
            onChange={(e) => {
              ensureIndex();
              setQuery(e.target.value);
            }}
            onFocus={() => {
              ensureIndex();
              if (matches.length > 0) setOpen(true);
            }}
            onKeyDown={onKeyDown}
            placeholder={placeholder}
            autoFocus={autoFocus}
            autoComplete="off"
            spellCheck={false}
            maxLength={40}
            aria-label="Search for a stock by ticker or company name"
            aria-expanded={open}
            aria-autocomplete="list"
            role="combobox"
            aria-controls="ticker-suggestions"
            className={`w-full rounded-[var(--radius-lg)] border pl-11 outline-none transition-all ${
              big ? 'py-3.5 pr-28 text-[15px]' : 'py-2.5 pr-20 text-[14px]'
            }`}
            style={{
              background: 'var(--surface)',
              borderColor: 'var(--border-strong)',
              color: 'var(--text-primary)',
              boxShadow: 'var(--shadow-sm)',
            }}
          />

          <button
            type="submit"
            disabled={isPending || !query.trim()}
            className={`absolute top-1/2 right-1.5 -translate-y-1/2 rounded-[var(--radius-md)] font-medium transition-all disabled:opacity-45 ${
              big ? 'px-4 py-2 text-[13.5px]' : 'px-3 py-1.5 text-[13px]'
            }`}
            style={{ background: 'var(--accent)', color: 'var(--text-inverse)' }}
          >
            {isPending ? 'Loading…' : 'Analyse'}
          </button>
        </div>
      </form>

      {open && matches.length > 0 && (
        <ul
          id="ticker-suggestions"
          role="listbox"
          className="ff-fade absolute z-20 mt-2 w-full overflow-hidden rounded-[var(--radius-lg)] border py-1"
          style={{
            background: 'var(--surface-overlay)',
            borderColor: 'var(--border-strong)',
            boxShadow: 'var(--shadow-lg)',
          }}
        >
          {matches.map(([symbol, name], i) => (
            <li key={symbol} role="option" aria-selected={i === highlighted}>
              <button
                type="button"
                onMouseEnter={() => setHighlighted(i)}
                onClick={() => go(symbol)}
                className="flex w-full items-baseline gap-3 px-4 py-2.5 text-left transition-colors"
                style={{ background: i === highlighted ? 'var(--accent-soft)' : 'transparent' }}
              >
                <span
                  className="tabular w-16 shrink-0 font-mono text-[13px] font-semibold"
                  style={{ color: 'var(--text-primary)' }}
                >
                  {symbol}
                </span>
                <span className="truncate text-[13px]" style={{ color: 'var(--text-secondary)' }}>
                  {name}
                </span>
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
